// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package s3_service

import (
	"github.com/aws/aws-sdk-go/aws/session"
	"github.com/aws/aws-sdk-go/service/s3"
	"os"
)

// Injectors from wire.go:

func InitializeFS() FS {
	fs := GetFS()
	return fs
}

// wire.go:

func GetFS() FS {

	s3Session := session.Must(session.NewSession())
	svc := s3.New(s3Session)

	return FS{
		svc:    svc,
		bucket: os.Getenv("AWS_BUCKET_NAME"),
	}
}
